"""'projectpathvar'

Revision ID: 5bfe50c17dfe
Revises: a41d44eba260
Create Date: 2020-05-25 19:07:48.113991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bfe50c17dfe'
down_revision = 'a41d44eba260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'path')
    # ### end Alembic commands ###
