"""'urlpath'

Revision ID: e7f301795883
Revises: 5bfe50c17dfe
Create Date: 2020-05-25 20:00:31.633264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f301795883'
down_revision = '5bfe50c17dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('urlpath', sa.Text(), nullable=True))
    op.drop_column('project', 'path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('path', sa.TEXT(), nullable=True))
    op.drop_column('project', 'urlpath')
    # ### end Alembic commands ###
